{
  host,
  config,
  pkgs,
  lib,
  ...
}: let
  # Import keybinds and window rules
  keybindsModule = import ./keybinds.nix {
    inherit
      host
      config
      ;
  };
  windowrulesModule = import ./windowrules.nix {inherit host;};
  layoutModule = import ./layout.nix {};
  startupModule = import ./startup.nix {
    inherit
      host
      ;
  };
in {
  # Install Niri and related packages
  home.packages = with pkgs; [
    niri
    udiskie
    xwayland-satellite
    swww
    grim
    slurp
    wl-clipboard
    swappy
    xdg-desktop-portal-gnome
  ];

  # Generate Niri config.kdl
  xdg.configFile."niri/config.kdl".text = ''
    // Niri Configuration for ${host}
    // Generated by NixOS configuration

    ${layoutModule}

    output "eDP-1" {
        mode "5120x2160@120"
        scale 1.0
        position x=0 y=0 
    }

    ${keybindsModule}

    ${windowrulesModule}

    ${startupModule}

    environment {
      XDG_CURRENT_DESKTOP "niri"
      GTK_USE_PORTAL "1"
      MOZ_ENABLE_WAYLAND "1"
      QT_QPA_PLATFORM "wayland"
      ELECTRON_OZONE_PLATFORM_HINT "wayland"
      QT_QPA_PLATFORMTHEME "gtk3"
      QT_QPA_PLATFORMTHEME_QT6 "gtk3"
      TERMINAL "ghostty"
      XCURSOR_THEME "Bibata-Modern-Ice"
      XCURSOR_SIZE "24"
    }

    hotkey-overlay {
        skip-at-startup
    }

    prefer-no-csd

    screenshot-path "~/Pictures/Screenshots/Screenshot from %Y-%m-%d %H-%M-%S.png"
  '';

  # Systemd services for Niri session
  systemd.user.targets.niri-session = {
    Unit = {
      Description = "Niri compositor session";
      Documentation = "man:systemd.special(7)";
      BindsTo = "graphical-session.target";
      Wants = "graphical-session-pre.target";
      After = "graphical-session-pre.target";
    };
  };

  # XWayland satellite service for X11 app support
  systemd.user.services.xwayland-satellite = {
    Unit = {
      Description = "Xwayland outside Wayland";
      BindsTo = "graphical-session.target";
      After = "graphical-session.target";
    };
    Service = {
      Type = "notify";
      NotifyAccess = "all";
      ExecStart = "${pkgs.xwayland-satellite}/bin/xwayland-satellite";
      StandardOutput = "journal";
      Restart = "on-failure";
    };
    Install.WantedBy = ["graphical-session.target"];
  };

  # XDG Desktop Portal services - properly configured for screen sharing
  systemd.user.services.xdg-desktop-portal = {
    Unit = {
      Description = "Portal service";
      After = [
        "graphical-session.target"
        # "pipewire.service"
      ];
      PartOf = ["graphical-session.target"];
    };
    Service = {
      Type = "dbus";
      BusName = "org.freedesktop.portal.Desktop";
      ExecStart = "${pkgs.xdg-desktop-portal}/libexec/xdg-desktop-portal";
      Restart = "on-failure";
      Environment = [
        "XDG_CURRENT_DESKTOP=niri"
        "WAYLAND_DISPLAY=wayland-1"
      ];
    };
    Install.WantedBy = ["graphical-session.target"];
  };

  systemd.user.services.xdg-desktop-portal-gnome = {
    Unit = {
      Description = "Portal service (GNOME implementation)";
      After = [
        "graphical-session.target"
        # "pipewire.service"
      ];
      PartOf = ["graphical-session.target"];
      Requires = []; # ["pipewire.service"];
    };
    Service = {
      Type = "dbus";
      BusName = "org.freedesktop.impl.portal.desktop.gnome";
      ExecStart = "${pkgs.xdg-desktop-portal-gnome}/libexec/xdg-desktop-portal-gnome";
      Restart = "on-failure";
      Environment = [
        "XDG_CURRENT_DESKTOP=niri"
      ];
    };
    Install.WantedBy = ["graphical-session.target"];
  };

  systemd.user.services.xdg-desktop-portal-gtk = {
    Unit = {
      Description = "Portal service (GTK/GNOME implementation)";
      After = [
        "graphical-session.target"
      ];
      PartOf = ["graphical-session.target"];
    };
    Service = {
      Type = "dbus";
      BusName = "org.freedesktop.impl.portal.desktop.gtk";
      ExecStart = "${pkgs.xdg-desktop-portal-gtk}/libexec/xdg-desktop-portal-gtk";
      Restart = "on-failure";
    };
    Install.WantedBy = ["graphical-session.target"];
  };

  # XDG Desktop Portal configuration for Niri
  xdg.configFile."xdg-desktop-portal/portals.conf".text = ''
    [preferred]
    default=gtk
    org.freedesktop.impl.portal.FileChooser=gtk
    org.freedesktop.impl.portal.Screenshot=gnome
    org.freedesktop.impl.portal.ScreenCast=gnome
  '';

  xdg.configFile."xdg-desktop-portal/niri-portals.conf".text = ''
    [preferred]
    default=gtk
    org.freedesktop.impl.portal.FileChooser=gtk
    org.freedesktop.impl.portal.Screenshot=gnome
    org.freedesktop.impl.portal.ScreenCast=gnome
  '';

  # Place wallpapers in home directory
  home.file = {
    "Pictures/Wallpapers" = {
      source = ../../wallpapers;
      recursive = true;
    };
  };
}
